# Site settings
title: tomrlh
email: tomrlh.tm@gmail.com
description: > # Writer Theme is a responsive template
 A developer submerged in web development technologies, focused in Java ecosystem, and other programmer stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "tomurlh.com" # the base hostname & protocol for your site
github_username: tomrlh
enable_retina: false
permalink: /:categories/:title
markdown: kramdown
highlighter: rouge
plugins:
  - jemoji
  - jekyll-seo-tag
defaults:
  -
   scope:
     path: ""
   values:
     author: "tomrlh"
     layout: index
     lang: en
     base-url: "/"
  -
   scope:
     path: pt
   values:
     author: "tomrlh"
     lang: pt
     base-url: "/pt/"
# Build settings
# markdown: kramdown
  