# Site settings
title: tomrlh
email: tomrlh.tm@gmail.com
description: > # Writer Theme is a responsive template
 focussed on typography, minimal design and quality photography built using the Jekyll platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username: tomrlh
enable_retina: false
permalink: /:categories/:title
markdown: kramdown
plugins:
  - jemoji
defaults:
  -
   scope:
     path: ""
   values:
     author: "tomrlh"
     layout: index
     lang: en
     base-url: "/"
  -
   scope:
     path: pt
   values:
     author: "tomrlh"
     lang: pt
     base-url: "/pt/"
# Build settings
# markdown: kramdown
  